spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}
    username: ${DB_USERNAME}
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC-3
        show_sql: true
        type: trace
        use_sql_comments: false